model_list:
  - gpt-4.1
#  - gpt-4.1-mini
#  - gpt-4.1-nano
  - gpt-4o
#  - gpt-4o-mini
#  - gpt-5
#  - gpt-5.1
#  - gpt-5.1-chat-latest
#  - gpt-5-chat-latest
#  - gpt-5-mini
#  - gpt-5-nano
#  - o1-mini
#  - o3
#  - o3-mini
# - o4-mini
temperature: 0.1
output_dir: results
prompts_dir: prompts

